# Generated by Django 5.1.4 on 2025-01-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toutiao_user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ttuser",
            name="user_agent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
